theme: jekyll-theme-hacker
title: dephcon.net
description: >- # this means to ignore newlines until "baseurl:"
  Fix it until it breaks
baseurl: "" # the subpath of your site, e.g. /blog
github_username: dephcon
linkedin_username: matt-smith-571a5640
github:
  is_project_page: false
  
